services:
  app:
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    volumes:
      - "${DB_DATA_PATH}:/var/lib/postgresql/data"
    env_file:
      - .env
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
